//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RawForms.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillInfo
    {
        public int BillID { get; set; }
        public string BillNumber { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> BillTypeID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual BillType BillType { get; set; }
        public virtual CustomerInfo CustomerInfo { get; set; }
    }
}
