//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RawForms.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductVariant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductVariant()
        {
            this.ProductInfoes = new HashSet<ProductInfo>();
        }
    
        public int VariantID { get; set; }
        public int SubTypeID { get; set; }
        public string VariantName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInfo> ProductInfoes { get; set; }
        public virtual ProductSubType ProductSubType { get; set; }
    }
}
