//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RawForms.Connection
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShopInfo
    {
        public int ShopID { get; set; }
        public string ShopName { get; set; }
        public string ShopAddress { get; set; }
        public string ZIP { get; set; }
        public string State { get; set; }
        public string Dist { get; set; }
        public string City { get; set; }
        public string PhoneNo { get; set; }
        public string Gstn { get; set; }
    }
}
